export const serviceCities = [
  "Paris",
  "Rome",
  "Florence",
  "Milan",
  "London",
  "Interlaken",
  "Jungfrau",
  "Zermatt",
  "Annecy",
  "Lisbon",
  "Barcelona",
  "Hawaii",
  "Bali",
  "Bangkok",
  "Beverly Hills",
  "Tokyo",
  "Osaka",
  "Kyoto",
  "Shanghai",
  "Beijing",
  "Chengdu",
  "Amsterdam",
  "Berlin",
  "Vienna",
];

export const serviceCitiesTimezones: Record<string, string> = {
  Paris: "Europe/Paris",
  Rome: "Europe/Rome",
  Florence: "Europe/Rome",
  Milan: "Europe/Rome",
  London: "Europe/London",
  Interlaken: "Europe/Zurich",
  Jungfrau: "Europe/Zurich",
  Zermatt: "Europe/Zurich",
  Annecy: "Europe/Paris",
  Lisbon: "Europe/Lisbon",
  Barcelona: "Europe/Madrid",
  Hawaii: "Pacific/Honolulu",
  Bali: "Asia/Makassar",
  Bangkok: "Asia/Bangkok",
  "Beverly Hills": "America/Los_Angeles",
  Tokyo: "Asia/Tokyo",
  Osaka: "Asia/Tokyo",
  Kyoto: "Asia/Tokyo",
  Shanghai: "Asia/Shanghai",
  Beijing: "Asia/Shanghai",
  Chengdu: "Asia/Shanghai",
  Amsterdam: "Europe/Amsterdam",
  Berlin: "Europe/Berlin",
  Vienna: "Europe/Vienna",
};
